Rename GDK config hash -> hash_setting
This will fix pry not working since `hash` appears to be used with `ls`:

```
$ pry -Ilib -rgdk
[1] pry(main)> conf = GDK.config
=> #<GDK::ConfigSettings slug:>
[2] pry(main)> ls conf.geo
ArgumentError: wrong number of arguments (given 0, expected 1)
from /home/git/gdk/lib/gdk/config_settings.rb:31:in `hash'
```