Work around XCode 14 issue with pg_query and ffi-yajl
XCode 14 causes the Ruby interpreter to drop the
`-Wl,-undefined,dynamic_lookup` flags in the `DLDFLAGS`, which are
passed in the final step to link a shared library of a native gems.
While this flag is still supported, the following warning causes the
`configure` step to omit these flags:

```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```

As a result, Ruby interpreters compiled under XCode 14 omit this
linker flag. However, this breaks some native gems, such as `pg_query`
and `ffi-yajl`, which can no longer find the symbols they need:

```
linking shared-object pg_query/pg_query.bundle
Undefined symbols for architecture arm64:
  "Init_pg_query", referenced from:
     -exported_symbol[s_list] command line option
     (maybe you meant: _Init_pg_query)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This commit sets the `bundle config` to include the dynamic lookup
linker flag for `pg_query` and `ffi-yajl`. This avoids needing to
recompile the Ruby interpreter in
https://gitlab.com/gitlab-org/gitlab-development-kit/-/merge_requests/2745.

The proper upstream fixes have been submitted here:

* https://github.com/pganalyze/pg_query/pull/256/
* https://github.com/chef/ffi-yajl/pull/114