Upgrade CI to use PostgreSQL 11
PostgreSQL 10 no longer works because GitLab depends on partitioning
features only present in PostgreSQL 11. From
https://gitlab.com/gitlab-org/gitlab-development-kit/-/jobs/613856156,
we see this error:

```
ERROR:  unrecognized partitioning strategy "hash"
```